spring.application.name=all

# 1. ALLOW RAILWAY TO DYNAMICALLY ASSIGN THE ROUTING PORT
server.port=${PORT:8080}

# 2. INTERNAL DATABASE CONNECTION (Fast & Secure inside Railway)
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=jDDrrGgDnnJaylOpYcupEybKWsuMSkMB
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema Configuration
spring.jpa.properties.hibernate.default_schema=library
